import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navigation from "@/components/navbar";
import { Flowbite, Footer } from "flowbite-react";
import { Head } from "next/document";
import { use } from "react";
import { cookies } from "next/headers";
import AppFooter from "@/components/footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {



  return (
    <html lang="en" >
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased dark:bg-gray-900`}
      >
        <Flowbite
          theme={{
            theme: {
              navbar: {
                root: {
                  base: "bg-white px-2 py-2.5 dark:border-gray-700 dark:bg-gray-800 sm:px-4 max-w-screen-2xl mx-auto dark:bg-gray-900",
                },
                collapse: {
                  base: "w-full lg:block lg:w-auto",
                },
                link: {
                  base: "block py-2 pr-4 pl-3 lg:p-0",
                  active: {
                    on: "bg-blue-700 text-white dark:text-white md:bg-transparent md:text-blue-700",
                    off: "border-b border-gray-100 text-gray-700 hover:bg-gray-50 dark:border-gray-700 dark:text-gray-400 dark:hover:bg-gray-700 dark:hover:text-white lg:border-0 lg:hover:bg-transparent lg:hover:text-blue-700 lg:dark:hover:bg-transparent lg:dark:hover:text-white",
                  },
                  disabled: {
                    on: "text-gray-400 hover:cursor-not-allowed dark:text-gray-600",
                    off: "",
                  },
                },
                toggle: {
                  base: "inline-flex items-center rounded-lg p-2 text-sm text-gray-500 hover:bg-gray-100 focus:outline-none focus:ring-2 focus:ring-gray-200 dark:text-gray-400 dark:hover:bg-gray-700 dark:focus:ring-gray-600 lg:hidden",
                  icon: "h-6 w-6 shrink-0",
                },
              },
              badge: {
                root: {
                  color: {
                    info: "bg-blue-100 text-blue-800 dark:bg-blue-200 dark:text-blue-800 group-hover:bg-blue-200 dark:group-hover:bg-blue-300",
                  },
                  size: {
                    xs: "py-1 px-2 text-xs",
                  },
                },
              },
              button: {
                color: {
                  gray: "text-gray-900 bg-white border border-gray-200 enabled:hover:bg-gray-100 enabled:hover:text-blue-700 :ring-blue-700 focus:text-blue-700 dark:bg-transparent dark:text-gray-400 dark:border-gray-600 dark:enabled:hover:text-white dark:enabled:hover:bg-gray-700 focus:ring-2",
                  info: "text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:ring-blue-300 dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800",
                },
                outline: {
                  color: {
                    gray: "border border-gray-200 dark:border-gray-500",
                  },
                },
              },
              checkbox: {
                root: {
                  base: "h-4 w-4 rounded border border-gray-300 bg-gray-100 focus:ring-2 focus:ring-blue-500 dark:border-gray-600 dark:bg-gray-700 dark:ring-offset-gray-800 dark:focus:ring-blue-600 text-blue-600",
                },
              },
              progress: {
                color: {
                  blue: "bg-blue-600",
                },
              },
              radio: {
                root: {
                  base: "h-4 w-4 border border-gray-300 focus:ring-2 focus:ring-blue-500 dark:border-gray-600 dark:bg-gray-700 dark:focus:bg-blue-600 dark:focus:ring-blue-600 text-blue-600",
                },
              },
              textInput: {
                field: {
                  input: {
                    colors: {
                      info: "border-blue-500 bg-blue-50 text-blue-900 placeholder-blue-700 focus:border-blue-500 focus:ring-blue-500 dark:border-blue-400 dark:bg-blue-100 dark:focus:border-blue-500 dark:focus:ring-blue-500",
                    },
                    withIcon: {
                      on: "!pl-12",
                    },
                  },
                },
              },
              toggleSwitch: {
                toggle: {
                  checked: {
                    color: {
                      blue: "bg-blue-700 border-blue-700",
                    },
                  },
                },
              },
            },
          }}
        >

          <Navigation />
          <div className="min-h-screen bg-white dark:bg-gray-900">
            {children}
          </div>
          <AppFooter />
        </Flowbite>

      </body>
    </html >
  );
}
